version: "3.7"

services:
  vue-knowledge-front:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: >
      bash -c "
          npm install
          npm run dev"
  
  storybook:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "6006:6006"
    environment:
      - BROWSER=none
    command: >
      bash -c "
          npm install
          npm run storybook -- --ci"

networks:
  default:
      name: vue-knowledge-front-network
      external: true
