version: "3.7"

services:
  vue-knowledge-front:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: >
      bash -c "
          npm install
          npm run dev"

networks:
  default:
      name: vue-knowledge-front-network
      external: true
